import { ApiProperty } from '@nestjs/swagger';

export class MessageResponseDto {
  @ApiProperty({
    description: 'The unique identifier of the message',
    example: '550e8400-e29b-41d4-a716-446655440000',
  })
  id: string;

  @ApiProperty({
    description: 'The ID of the user who sent the message',
    example: 'user123',
  })
  fromUserId: string;

  @ApiProperty({
    description: 'The ID of the user receiving the message',
    example: 'user456',
  })
  toUserId: string;

  @ApiProperty({
    description: 'The message content',
    example: 'Hey! How are you?',
  })
  content: string;

  @ApiProperty({
    description: 'The timestamp when the message was sent',
    example: '2024-01-15T10:30:00Z',
  })
  timestamp: Date;

  @ApiProperty({
    description: 'Whether the message has been read',
    example: false,
  })
  isRead: boolean;

  @ApiProperty({
    description: 'Whether the message was generated by AI',
    example: false,
  })
  isAIGenerated: boolean;
}
